import NavBar from "@/components/Nav/nav-bar";
import Footer from "@/components/footer";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratSans.variable} antialiased`}
        suppressHydrationWarning
      >
        <header className= "">
          <NavBar />
        </header>
        <main className="pt-24">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
